### ISSUE TITLE
Refactor to use Null Object Pattern

### ISSUE THREAD

**Issue by blackfist** [blackfist/windmill#12]
We have some duplication that needs to be DRYed out, in the `/api/config` and the `/api/config/:name` functions we have largely repeated the code. We could also use the null object pattern so that rather than doing an if valid_node_key? we just call for a GuaranteedEndpoint object which will either be a real endpoint from the database or it will be an object that conforms to the same api.

**Comment by sroberts** [comment]
Now I've gotta go read up on null object pattern.

**Comment by blackfist** [comment]
Check out this video: https://youtu.be/9lv2lBq6x4A
