### ISSUE TITLE
Authentication.

### ISSUE THREAD

**Issue by blackfist** [blackfist/windmill#27]
People accessing the web interface should be required to authenticate. The OmniAuth gem seems like the right tool for the job. I'm thinking we use a static file with a list of email addresses that are allowed to do things and then provide multiple OAuth providers that a user can use to gain access to the app.

Omniauth: https://github.com/intridea/omniauth
Heroku: https://github.com/heroku/omniauth-heroku
GitHub: https://github.com/intridea/omniauth-github

**Comment by sroberts** [comment]
@blackfist I'd agree, seems like it'd do just what's necessary.

**Comment by blackfist** [comment]
Closed in d5659b8d309da2a2e4115d9734b73c81bebcdff4
